name: Create/Update services environment variables to AWS SSM

on: 
  push:
    branches:
      - feat/test
  workflow_dispatch:
    inputs:
      env:
        description: "Select the environment for which variable change is required"
        required: true
        type: choice
        options:
          - dev
          - prod

      service:
        description: "Select the service for which SSM changes needed"
        required: true
        type: choice
        options:
          - frontend
          - backend 

      kv_input:
        description: "Define the parameter name and value in format: key=value"
        required: true

jobs:
  update-ssm:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for authenticating with AWS using OIDC
      contents: read  # Required to check out the repo

    steps:
      - name: Construct parameter path
        id: path
        run: echo "PARAM_PATH=/${{ github.event.inputs.env }}/${{ github.event.inputs.service }}" >> $GITHUB_ENV
